SPEEDUP = 2.0

set_encodings("utf-8")
set_policy("build.warning", true)
set_languages("c++20")
set_optimize("fastest")

target("mmdevapi_x64")
set_kind("shared")
set_arch("x64")
set_filename("MMDevAPI-win64-" .. SPEEDUP .. ".dll")
add_files("MMDevAPI/x64/mmdevapi.cpp", "MMDevAPI/x64/mmdevapi.def", "MMDevAPI/x64/mmdevapi_asm.asm")
add_links("ole32", "user32")
add_defines("SPEEDUP=" .. SPEEDUP)

target("mmdevapi_x86")
set_kind("shared")
set_arch("x86")
set_filename("MMDevAPI-win32-" .. SPEEDUP .. ".dll")
add_files("MMDevAPI/x86/mmdevapi.cpp", "MMDevAPI/x86/mmdevapi.def")
add_links("ole32", "user32")
add_defines("SPEEDUP=" .. SPEEDUP)

target("dsound_x64")
set_kind("shared")
set_arch("x64")
set_filename("dsound-win64-" .. SPEEDUP .. ".dll")
add_files("dsound/x64/dsound.cpp", "dsound/x64/dsound.def", "dsound/x64/dsound_asm.asm")
add_links("ole32", "user32", "dsound", "dxguid")
add_defines("SPEEDUP=" .. SPEEDUP)

target("dsound_x86")
set_kind("shared")
set_arch("x86")
set_filename("dsound-win32-" .. SPEEDUP .. ".dll")
add_files("dsound/x86/dsound.cpp", "dsound/x86/dsound.def")
add_links("ole32", "user32", "dsound", "dxguid")
add_defines("SPEEDUP=" .. SPEEDUP)
